ARM: davinci: fix for build breakage for tnetv107x platforms
Fix the following build breakage and section mismatch error. This build
break will comes only on removal of NEED_MACH_GPIO_H select option for
ARCH-DAVINCI.

arch/arm/mach-davinci/board-tnetv107x-evm.c:283:15: error:
'davinci_timer_init' undeclared here (not in a function)
arch/arm/mach-davinci/board-tnetv107x-evm.c:285:15: error:
'davinci_init_late' undeclared here (not in a function)
make[1]: *** [arch/arm/mach-davinci/board-tnetv107x-evm.o] Error 1

Signed-off-by: Philip Avinash <avinashphilipk@gmail.com>